name: 'Metagen GitHub Action'
description: 'Github action generating meta files for Unity using JS.'
branding:
    icon: 'anchor'
    color: 'green'
inputs:
  seed:
    description: 'seed string, e.g. package name. defaults to cwd'
    required: false
  files:
    description: 'files to generate .meta files for. default: use package.json .files as input'
    required: false
outputs:
  metafiles:
    description: 'list of generated metafiles'
runs:
  using: 'node16'
  main: 'index.js'
