name: 'Metagen GitHub Action'
description: 'Github action generating meta files for Unity using JS.'
branding:
    icon: 'anchor'
    color: 'green'
inputs:
  seed:
    description: 'seed string, e.g. package name. defaults to cwd'
    required: false
  directory:
    description: 'directory containing files that needs to have meta files generated'
    required: false
outputs:
  metafiles:
    description: 'list of generated metafiles'
runs:
  using: 'node16'
  main: 'action/index.js'
